// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.extensions.fxmonitor.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "4b6c5f4a-e0c3-d246-93f9-7ebd3279df58");
user_pref("app.update.download.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1598136074);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 931840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1598136043);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1d14142e-61c9-e843-9243-5602e07edc10}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1598136080814");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1598137907814");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1598136048336");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1598139648336");
user_pref("browser.search.region", "UA");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190409155332");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 3472);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190409155332");
user_pref("browser.startup.homepage_override.mstone", "66.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1598136046547");
user_pref("devtools.debugger.prefs-schema-version", "1.0.5");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("distribution.iniFile.exists.appversion", "66.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "526f8a1d3ad34642a92a68ce9ca8ada6");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "66.0.3");
user_pref("extensions.lastPlatformVersion", "66.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"4b3a9fd8-bf87-d247-9710-62cc3aca0fba\",\"webcompat@mozilla.org\":\"8a3786e8-00a8-7f47-a877-9c8819d81049\",\"formautofill@mozilla.org\":\"d42be0bc-af41-7242-b85e-2ee18b5a14a1\",\"webcompat-reporter@mozilla.org\":\"de79cc46-af14-624a-b217-cd2771d4b16a\"}");
user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "0d38e27d-25ab-ba45-9cf2-b28e03bb0b65");
user_pref("security.sandbox.plugin.tempDirSuffix", "d296d822-80c2-6d47-b351-4b79c9e05637");
user_pref("services.blocklist.addons.checked", 1598136046);
user_pref("services.blocklist.gfx.checked", 1598136046);
user_pref("services.blocklist.onecrl.checked", 1598136046);
user_pref("services.blocklist.pinning.checked", 1598136046);
user_pref("services.blocklist.plugins.checked", 1598136046);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1598041323581\"");
user_pref("services.settings.last_update_seconds", 1598136046);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1598136046);
user_pref("services.settings.main.language-dictionaries.last_check", 1598136046);
user_pref("services.settings.main.sites-classification.last_check", 1598136046);
user_pref("services.settings.main.tippytop.last_check", 1598136046);
user_pref("services.sync.client.name", "johnpeppe’s Firefox on Dzhons-MacBook-Pro");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1598136042);
user_pref("toolkit.telemetry.cachedClientID", "b692ec2a-2be9-494f-9694-a09705d09646");
user_pref("toolkit.telemetry.previousBuildID", "20190409155332");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
